In [1]:
!pip install pandas

In [2]:
import pandas as pd
fruits=["蘋果", "橘子", "梨子", "櫻桃"]
s1=pd.Series(fruits)
print(type(s1))
print(s1)
print(s1.index)
print(s1.values)
print()
quantities=[15, 33, 45, 55]
s2=pd.Series(quantities,fruits)
print(type(s2))
print(s2)
print(s2.index)
print(s2.values)
print(s2['蘋果'])

<class 'pandas.core.series.Series'>
0    蘋果
1    橘子
2    梨子
3    櫻桃
dtype: object
RangeIndex(start=0, stop=4, step=1)
['蘋果' '橘子' '梨子' '櫻桃']

<class 'pandas.core.series.Series'>
蘋果    15
橘子    33
梨子    45
櫻桃    55
dtype: int64
Index(['蘋果', '橘子', '梨子', '櫻桃'], dtype='object')
[15 33 45 55]
15


In [3]:
import pandas as pd
fruits=["蘋果", "橘子", "梨子", "櫻桃"]
quantities=[15, 33, 45, 55]
s3=pd.Series(quantities)
print(type(s3))
print(s3)
print(s3.index)
print(s3.values)
print()
dict4={"蘋果":15, "橘子":33, "梨子":45, "櫻桃":55}
s4=pd.Series(dict4)
print(type(s4))
print(s4)
print(s4.index)
print(s4.values)

<class 'pandas.core.series.Series'>
0    15
1    33
2    45
3    55
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[15 33 45 55]

<class 'pandas.core.series.Series'>
蘋果    15
橘子    33
梨子    45
櫻桃    55
dtype: int64
Index(['蘋果', '橘子', '梨子', '櫻桃'], dtype='object')
[15 33 45 55]


In [4]:
import pandas as pd
quantities = [15, 33, 45, 55]
s5 = pd.Series(quantities)
print(s5.count( ))
print(s5.median( ))
print(s5.mean( ))
print(s5.min( ))
print(s5.max( ))
print("---------")
print(s5.describe( ))
print(s5.var( ))
print(s5.std ( ))
print(s5.apply(lambda x:x**2))

4
39.0
37.0
15
55
---------
count     4.000000
mean     37.000000
std      17.204651
min      15.000000
25%      28.500000
50%      39.000000
75%      47.500000
max      55.000000
dtype: float64
296.0
17.204650534085253
0     225
1    1089
2    2025
3    3025
dtype: int64


In [5]:
import pandas as pd
data1={'name':['Tom','Jack','Stella','Ricky'],'age':[28,34,29,42],'gender':['m','m','f','m']}
df1=pd.DataFrame(data1)
print(df1)
df2=pd.DataFrame(data1,index=['emp1','emp2','emp3','emp4'])
print(df2)
df3=pd.DataFrame(data1,index=range(1,5),columns=(['name','gender']))
print(df3)
df4=pd.DataFrame(data1,index=range(1,5),columns=(['name','age']))
print(df4)

     name  age gender
0     Tom   28      m
1    Jack   34      m
2  Stella   29      f
3   Ricky   42      m
        name  age gender
emp1     Tom   28      m
emp2    Jack   34      m
emp3  Stella   29      f
emp4   Ricky   42      m
     name gender
1     Tom      m
2    Jack      m
3  Stella      f
4   Ricky      m
     name  age
1     Tom   28
2    Jack   34
3  Stella   29
4   Ricky   42


In [6]:
import pandas as pd
data2=[{'Name':'Tom', 'Age': 28, 'Gender':'M'},
      {'Name':'Jack', 'Age': 34, 'Gender':'M'},
      {'Name':'Stella', 'Age': 29, 'Gender':'F'},
      {'Name':'Ricky', 'Age': 42, 'Gender':'M'}]
df1=pd.DataFrame(data2)
print(df1)
df2=pd.DataFrame(data2,index=['emp1','emp2','emp3','emp4'],columns=(['Name','Age','Gender']))
print(df2)
df3=pd.DataFrame(data2,index=range(1,5),columns=(['Name','Gender']))
print(df3)
df4=pd.DataFrame(data2,index=range(1,5),columns=(['Name','Age']))
print(df4)

     Name  Age Gender
0     Tom   28      M
1    Jack   34      M
2  Stella   29      F
3   Ricky   42      M
        Name  Age Gender
emp1     Tom   28      M
emp2    Jack   34      M
emp3  Stella   29      F
emp4   Ricky   42      M
     Name Gender
1     Tom      M
2    Jack      M
3  Stella      F
4   Ricky      M
     Name  Age
1     Tom   28
2    Jack   34
3  Stella   29
4   Ricky   42


In [7]:
import pandas as pd
data3=[['Tom',28,'m'],['Jack',34,'m'],['Stella',29,'f'],['Ricky',42,'m']]
df1=pd.DataFrame(data3)
print(df1)
df2=pd.DataFrame(data3,index=range(1,5),columns=('name','age','gender'))
print(df2)

        0   1  2
0     Tom  28  m
1    Jack  34  m
2  Stella  29  f
3   Ricky  42  m
     name  age gender
1     Tom   28      m
2    Jack   34      m
3  Stella   29      f
4   Ricky   42      m


In [8]:
import pandas as pd
import numpy as np
data4=np.array([['Tom', 28, 'M'],['Jack',34,'M'],['Stella',29,'F'],['Ricky',42,'M']])
df1=pd.DataFrame(data4)
print(df1)
df2=pd.DataFrame(data4,index=range(1,5),columns=['Name','Age','Gender'])
print(df2)

        0   1  2
0     Tom  28  M
1    Jack  34  M
2  Stella  29  F
3   Ricky  42  M
     Name Age Gender
1     Tom  28      M
2    Jack  34      M
3  Stella  29      F
4   Ricky  42      M


In [9]:
import pandas as pd
cindex=range(1,5)
data5={'Name' : pd.Series(['Tom', 'Jack', 'Stella', 'Ricky'],index=cindex),
                        'Age' : pd.Series([28,34,29,42],index=cindex),
                        'Gender' : pd.Series(['M', 'M', 'F', 'M'],index=cindex)}
df1 = pd.DataFrame(data5,index=cindex)
print(df1)
data6 = [pd.Series(['Tom', 28, 'M'],index=['name','age','gender']),
         pd.Series(['Jack', 34, 'M'],index=['name','age','gender']),
         pd.Series(['Stella', 29, 'F'],index=['name','age','gender']),
         pd.Series(['Ricky', 42, 'M'],index=['name','age','gender'])]
df2 = pd.DataFrame(data6,index=range(1,5))
print(df2)

     Name  Age Gender
1     Tom   28      M
2    Jack   34      M
3  Stella   29      F
4   Ricky   42      M
     name  age gender
1     Tom   28      M
2    Jack   34      M
3  Stella   29      F
4   Ricky   42      M


In [10]:
rindex=range(1,5)
s1=pd.Series(['Tom','Jack','Stella','Ricky'],index=rindex)
s2=pd.Series([28,34,29,42],index=rindex)
s3=pd.Series(['M','M','F','M'],index=rindex)
data7={'name':s1,'age':s2,'gender':s3}
data8=pd.DataFrame(data7,index=rindex)
print(data8)

     name  age gender
1     Tom   28      M
2    Jack   34      M
3  Stella   29      F
4   Ricky   42      M


In [11]:
import pandas as pd
data = {"country":["Brazil","Russia","India","China","SouthAfrica"],
        "population":[200,144,1252,1357,55],
        "area":[8515767,17098242,3287590,9596961,1221037],
        "capital":["Brasilia","Moscow","NewDelhi","Beijing","Pretoria"]}
df=pd.DataFrame(data,index=['BR','RU','IN','CH','SA'])
print(df)
df.to_html('brics.html')
df.to_csv('brics.csv')
df.to_csv('brics2.csv',header=False)
df.to_json('brics.json')

        country  population      area   capital
BR       Brazil         200   8515767  Brasilia
RU       Russia         144  17098242    Moscow
IN        India        1252   3287590  NewDelhi
CH        China        1357   9596961   Beijing
SA  SouthAfrica          55   1221037  Pretoria


In [12]:
import pandas as pd
data = {"name": ["中正區", "板橋區", "桃園區", "北屯區", "安南區", "三民區", "大安區", "永和區", "八德區", "前鎮區", "鳳山區", "信義區", "新店區"],
        "population": [159598, 551452, 441287, 275207, 192327, 343203, 309835, 222531, 198473, 189623, 359125, 225561, 302070],
        "city": ["台北市", "新北市", "桃園市", "台中市", "台南市", "高雄市", "台北市", "新北市", "桃園市", "高雄市", "高雄市", "台北市", "新北市"]}
rows = ["first", "second", "third", "fourth", "fifth", "sixth", "seventh","eigth", "ninth", "tenth", "eleventh", "twelvth", "thirteenth"]
df2=pd.DataFrame(data,index=rows)
print(df2)
df2.to_html('area.html')
df2.to_csv('area.csv')
df2.to_json('area.json',force_ascii=False)

           name  population city
first       中正區      159598  台北市
second      板橋區      551452  新北市
third       桃園區      441287  桃園市
fourth      北屯區      275207  台中市
fifth       安南區      192327  台南市
sixth       三民區      343203  高雄市
seventh     大安區      309835  台北市
eigth       永和區      222531  新北市
ninth       八德區      198473  桃園市
tenth       前鎮區      189623  高雄市
eleventh    鳳山區      359125  高雄市
twelvth     信義區      225561  台北市
thirteenth  新店區      302070  新北市


In [13]:
import pandas as pd
df1=pd.read_csv('brics.csv')
print(df1)
print()
df2=pd.read_csv('brics.csv',header=None,index_col=0)
print(df2)
print()

  Unnamed: 0      country  population      area   capital
0         BR       Brazil         200   8515767  Brasilia
1         RU       Russia         144  17098242    Moscow
2         IN        India        1252   3287590  NewDelhi
3         CH        China        1357   9596961   Beijing
4         SA  SouthAfrica          55   1221037  Pretoria

               1           2         3         4
0                                               
NaN      country  population      area   capital
BR        Brazil         200   8515767  Brasilia
RU        Russia         144  17098242    Moscow
IN         India        1252   3287590  NewDelhi
CH         China        1357   9596961   Beijing
SA   SouthAfrica          55   1221037  Pretoria



In [14]:
import pandas as pd
df1=pd.read_csv('brics.csv')
print(df1)
print('--------------------------')
cols=['code','country','population','area','capital']
df2 = pd.read_csv("brics2.csv", header=None, names=cols)
print(df2)
print('--------------------------')
cols2=['country','population','area','capital']
df3 = pd.read_csv("brics2.csv", names=cols2, index_col=0)
print(df3)
print('--------------------------')

  Unnamed: 0      country  population      area   capital
0         BR       Brazil         200   8515767  Brasilia
1         RU       Russia         144  17098242    Moscow
2         IN        India        1252   3287590  NewDelhi
3         CH        China        1357   9596961   Beijing
4         SA  SouthAfrica          55   1221037  Pretoria
--------------------------
  code      country  population      area   capital
0   BR       Brazil         200   8515767  Brasilia
1   RU       Russia         144  17098242    Moscow
2   IN        India        1252   3287590  NewDelhi
3   CH        China        1357   9596961   Beijing
4   SA  SouthAfrica          55   1221037  Pretoria
--------------------------
        country  population      area   capital
BR       Brazil         200   8515767  Brasilia
RU       Russia         144  17098242    Moscow
IN        India        1252   3287590  NewDelhi
CH        China        1357   9596961   Beijing
SA  SouthAfrica          55   1221037  Pretori

In [15]:
df1=pd.read_csv('area.csv')
print(df1)
print()
df2=pd.read_csv('area.csv',header=0,index_col=0)
print(df2)

    Unnamed: 0 name  population city
0        first  中正區      159598  台北市
1       second  板橋區      551452  新北市
2        third  桃園區      441287  桃園市
3       fourth  北屯區      275207  台中市
4        fifth  安南區      192327  台南市
5        sixth  三民區      343203  高雄市
6      seventh  大安區      309835  台北市
7        eigth  永和區      222531  新北市
8        ninth  八德區      198473  桃園市
9        tenth  前鎮區      189623  高雄市
10    eleventh  鳳山區      359125  高雄市
11     twelvth  信義區      225561  台北市
12  thirteenth  新店區      302070  新北市

           name  population city
first       中正區      159598  台北市
second      板橋區      551452  新北市
third       桃園區      441287  桃園市
fourth      北屯區      275207  台中市
fifth       安南區      192327  台南市
sixth       三民區      343203  高雄市
seventh     大安區      309835  台北市
eigth       永和區      222531  新北市
ninth       八德區      198473  桃園市
tenth       前鎮區      189623  高雄市
eleventh    鳳山區      359125  高雄市
twelvth     信義區      225561  台北市
thirteenth  新店區      302070  新北市


In [16]:
import pandas as pd
df1=pd.read_json('brics.json')
print(df1)
print()
df2=pd.read_json('area.json',encoding='big5')
print(df2)

        country  population      area   capital
BR       Brazil         200   8515767  Brasilia
RU       Russia         144  17098242    Moscow
IN        India        1252   3287590  NewDelhi
CH        China        1357   9596961   Beijing
SA  SouthAfrica          55   1221037  Pretoria



           name  population city
first       中正區      159598  台北市
second      板橋區      551452  新北市
third       桃園區      441287  桃園市
fourth      北屯區      275207  台中市
fifth       安南區      192327  台南市
sixth       三民區      343203  高雄市
seventh     大安區      309835  台北市
eigth       永和區      222531  新北市
ninth       八德區      198473  桃園市
tenth       前鎮區      189623  高雄市
eleventh    鳳山區      359125  高雄市
twelvth     信義區      225561  台北市
thirteenth  新店區      302070  新北市


In [17]:
!pip install lxml